language: go
sudo: false
go:
  - "1.11.x"
  - tip
os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
